server:
  ssl:
    key-store: C:\Users\Arsen\mykeys.jks
    key-store-password: 123123
    key-password: 123123
  port: 8443
spring:
  jms:
    template:
      default-destination: tacocloud.order.queue
  artemis:
    user: taco-cloud
    password: taco-cloud
    mode: native
    broker-url: tcp://localhost:61616
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: tacocloud.order
      routing-key: orderRoutingKey
  data:
    rest:
      base-path: /data-api
  jpa:
    open-in-view: false
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
      client:
        registration:
          <facebook>:
            clientId: 531411519562557
            clientSecret: 3070507b3e4c8ec4f1400335c70672fb
            scope: public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
            authorization-grant-type: authorization_code