spring:
  application:
    name: authorization-server

  jpa:
    open-in-view: false
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 9000
